Update app.py
the fix for small versioning conflict

to correct error that prevented image generation as reported back on Streamlit

Error was
The cosmic connection timed out! Error: module 'google.generativeai.types' has no attribute 'GenerateContentConfig'